name: CI
on:  
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_LOCATION: src/mapgie.github.io/
  PROJECT_FILE: mapgie.github.io.csproj
  BUILD_LOCATION: build/
  
jobs:  
  build:    
    runs-on: ubuntu-latest
    
    steps:    
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
              dotnet-version: 6.x.x
         
      - name: Publish with dotnet
        run: dotnet publish ${{ env.PROJECT_LOCATION }}${{ env.PROJECT_FILE }} --configuration Release --output ${{ env.BUILD_LOCATION }}
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ${{ env.BUILD_LOCATION }}wwwroot
